### ISSUE TITLE
Add default button styling

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#84]
```css
button {
    appearance: none;
    border: none;
    padding: 0;
    background-color: transparent;
    cursor: pointer;
    font-family: $primary-font;
    text-align: left;

    &:focus {
        outline: none;
    }
}
```
